langs: [en, de]
buttonPositions:
  button-1: [800, 1855]
  button-2: [1250, 1855]
  button-3: [1000, 1980]
  lang-button: [1611, 1700]
idleVideoSrc: ./videos/idle.mp4
scenarios:
  TreeFalls:
    videoSrc: ./videos/scene_1_0.mp4
    labels:
      AutonomousCar:
        position: [740, 890]
        color: rgb(118, 187, 255)
        width: 300
      Cyclist:
        position: [740, 1050]
        color: rgb(82, 255, 255)
        width: 250
      FallenTree:
        position: [360, 1055]
        color: rgb(166, 242, 107)
        width: 200
        align: right
    policyVideos:
      Utilitarian: ./videos/scene_1_1.mp4
      Protector: ./videos/scene_1_3.mp4
      Profit: ./videos/scene_1_2.mp4
  CarEntersLane:
    videoSrc: ./videos/scene_3_0.mp4
    labels:
      AutonomousCar:
        position: [1640, 970]
        color: rgb(118, 187, 255)
        width: 285
      LuxuryCar:
        position: [1435, 585]
        color: rgb(214, 67, 67)
        width: 250
      BusStop:
        position: [1665, 810]
        color: rgb(204, 204, 204)
        width: 250
      Truck:
        position: [1205, 825]
        color: rgb(193, 114, 99)
        width: 235
        align: right
    policyVideos:
      Utilitarian: ./videos/scene_3_1.mp4
      Protector: ./videos/scene_3_3.mp4
      Profit: ./videos/scene_3_2.mp4
  ChildRuns:
    videoSrc: ./videos/scene_2_0.mp4
    labels:
      AutonomousCar:
        position: [960, 1285]
        width: 355
        color: rgb(108, 162, 255)
      Ambulance:
        position: [950, 930]
        width: 200
        color: rgb(230, 230, 230)
      Child:
        position: [740, 1010]
        width: 195
        color: rgb(225, 124, 85)
      OtherCar:
        position: [405, 1235]
        width: 375
        color: rgb(187, 222, 242)
        align: right
    policyVideos:
      Utilitarian: ./videos/scene_2_1.mp4
      Protector: ./videos/scene_2_3.mp4
      Profit: ./videos/scene_2_2.mp4
