langs: [en, de]
buttonPositions:
  button-1: [800, 1855]
  button-2: [1250, 1855]
  button-3: [1000, 1980]
idleVideoSrc: /videos/idle.mp4
scenarios:
  TreeFalls:
    videoSrc: /videos/scene_1_0.mp4
    labels:
      AutonomousCar:
        position: [740, 890]
        color: rgb(118, 187, 255)
      Cyclist:
        position: [740, 1050]
        color: rgb(82, 255, 255)
      FallenTree:
        position: [270, 1055]
        color: rgb(166, 242, 107)
        align: right
    policyVideos:
      Utilitarian: /videos/scene_1_1.mp4
      Protector: /videos/scene_1_3.mp4
      Profit: /videos/scene_1_2.mp4
  CarEntersLane:
    videoSrc: /videos/scene_3_0.mp4
    labels:
      AutonomousCar:
        position: [1390, 1000]
      LuxuryCar:
        position: [1310, 610]
      Truck:
        position: [1620, 710]
      BusStop:
        position: [1050, 740]
    policyVideos:
      Utilitarian: /videos/scene_3_1.mp4
      Protector: /videos/scene_3_3.mp4
      Profit: /videos/scene_3_2.mp4
  ChildRuns:
    videoSrc: /videos/scene_2_0.mp4
    labels:
      AutonomousCar:
        position: [850, 1220]
      Ambulance:
        position: [980, 1020]
      Child:
        position: [660, 1040]
      OtherCar:
        position: [650, 1290]
    policyVideos:
      Utilitarian: /videos/scene_2_1.mp4
      Protector: /videos/scene_2_3.mp4
      Profit: /videos/scene_2_2.mp4
